version: "3.8"

services:
  duckdns:
    container_name: duckdns-test
    image: linuxserver/duckdns:latest
    environment:
      - TOKEN=${DUCKDNS_TOKEN}  # Replace with your DuckDNS token
      - SUBDOMAINS=${DUCK_DNS_SUBDOMAINS}  # Replace with your DuckDNS subdomain (e.g., mydomain)
      - TZ=America/Vancouver  # Replace with your timezone
    volumes:
      - /mnt/user/appdata/duckdns:/config  # Adjust the path if needed
    restart: unless-stopped
    network_mode: host