version: "3.3"

services:
  backup:
    image: mazzolino/restic
    container_name: restic
    hostname: restic_backup
    environment:
      RUN_ON_STARTUP: "true"
      BACKUP_CRON: "0 */12 * * *" # Twice daily, every 12 hours
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      RESTIC_BACKUP_SOURCES: /mnt/volumes
      RESTIC_COMPRESSION: auto
      RESTIC_BACKUP_ARGS: >-
        --tag restic-docker-appdata # Add tags, whatever you need to mark backups
        --verbose
      RESTIC_FORGET_ARGS: >-
        --keep-last 10
        --keep-daily 7
        --keep-weekly 5
        --keep-monthly 12
      TZ: America/Vancouver
    volumes:
      - /mnt/user/backups:/restic # Store backups in the new backups share
      - /mnt/user/backups/tmp-for-restore:/tmp-for-restore # Folder for restores
      - /mnt/user/appdata/docker:/mnt/volumes:ro # Read-only mount for Docker data
    security_opt:
      - no-new-privileges:true

  prune:
    image: mazzolino/restic
    container_name: restic-prune
    hostname: restic_backup
    environment:
      RUN_ON_STARTUP: "true"
      PRUNE_CRON: "0 0 4 * * *"
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      TZ: America/Vancouver
    security_opt:
      - no-new-privileges:true

  check:
    image: mazzolino/restic
    container_name: restic-check
    hostname: restic_backup
    environment:
      RUN_ON_STARTUP: "false"
      CHECK_CRON: "0 15 5 * * *"
      RESTIC_CHECK_ARGS: >-
        --read-data-subset=10%
      RESTIC_REPOSITORY: /restic
      RESTIC_PASSWORD: ${RESTIC_PASSWORD}
      TZ: America/Vancouver
    security_opt:
      - no-new-privileges:true
